import { images } from "./imagesRefrences";
export const ItemsData = [
  {
    id: 1,
    name: "Ash Double Bed",
    url: images.beds.kingSizebeds.kingSizebedOne,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 250.0,
  },
  {
    id: 2,
    name: "Andes Deco Semi Double Bed",
    url: images.beds.kingSizebeds.kingSizebedTwo,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 450.0,
  },
  {
    id: 3,
    name: "Brown Hardwood Double Bed",
    url: images.beds.kingSizebeds.kingSizebedThree,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 650.0,
  },
  {
    id: 4,
    name: "Cedar Double Bed",
    url: images.beds.kingSizebeds.kingSizebedFour,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 550.0,
  },
  {
    id: 5,
    name: "Deluxe Mahagony Double Bed",
    url: images.beds.kingSizebeds.kingSizebedFive,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 278.0,
  },
  {
    id: 6,
    name: "Green Elm wood Double Bed",
    url: images.beds.kingSizebeds.kingSizebedSix,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 250.0,
  },
  {
    id: 7,
    name: "Grey Fir Double Bed",
    url: images.beds.kingSizebeds.kingSizebedSeven,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 380.0,
  },
  {
    id: 8,
    name: "AlaskaHaven Storage Semi Double Bed",
    url: images.beds.kingSizebeds.kingSizebedEight,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 890.0,
  },
  {
    id: 9,
    name: "Partex Coushoned Double Bed",
    url: images.beds.kingSizebeds.kingSizebedNine,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 250.0,
  },
  {
    id: 10,
    name: "Vince Ottoman Double Bed",
    url: images.beds.kingSizebeds.kingSizebedTen,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 540.0,
  },
  {
    id: 11,
    name: "Supreme Oak Double Bed",
    url: images.beds.kingSizebeds.kingSizebedEleven,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 850.0,
  },
  {
    id: 12,
    name: "Vince Ottoman Double Bed",
    url: images.beds.kingSizebeds.kingSizebedTwelve,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 13,
    name: "luxuary Queen Size Bed",
    url: images.beds.queensizebeds.queensizebedsone,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 14,
    name: "luxuary Queen Size Bed",
    url: images.beds.queensizebeds.queensizebedstwo,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 15,
    name: "luxuary Queen Size Bed",
    url: images.beds.queensizebeds.queensizebedsthree,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 16,
    name: "luxuary Queen Size Bed",
    url: images.beds.queensizebeds.queensizebedsfour,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 17,
    name: "luxuary Queen Size Bed",
    url: images.beds.queensizebeds.queensizebedsfive,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 18,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedone,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 19,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedtwo,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 20,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedthree,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 21,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedfour,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 22,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedfive,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 23,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedsix,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 24,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedseven,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 25,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebedeight,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 460.0,
  },
  {
    id: 26,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebednine,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 650.0,
  },
  {
    id: 27,
    name: "luxuary Queen Size Bed",
    url: images.beds.singlebeds.singlebednine,
    generalCategery: "Beds",
    categery: "king size Beds",
    price: 120.0,
  },
  {
    id: 28,
    name: "Aarya Yellow Single Sofa",
    url: images.chairs.chairone,
    generalCategery: "Chairs",
    categery: "Chairs",
    price: 320.0,
  },
  {
    id: 29,
    name: "Aero Stylish Single Sofa",
    url: images.chairs.chairtwo,
    generalCategery: "Chairs",
    categery: "Chairs",
    price: 275.0,
  },
  {
    id: 30,
    name: "Draped Single Sofa",
    url: images.chairs.chairthree,
    generalCategery: "Chairs",
    categery: "Chairs",
    price: 360.0,
  },
  {
    id: 31,
    name: "Recliner Brown Single Sofa",
    url: images.chairs.chairfour,
    generalCategery: "Chairs",
    categery: "Chairs",
    price: 300.0,
  },
  {
    id: 32,
    name: "Safari Ash Single Sofa",
    url: images.chairs.chairfive,
    generalCategery: "Chairs",
    categery: "Chairs",
    price: 280.0,
  },
  {
    id: 33,
    name: "Sibeili Cane Sofa Set",
    url: images.chairs.chairsix,
    generalCategery: "Chairs",
    categery: "Chairs",
    price: 700.0,
  },
  {
    id: 34,
    name: "Vester Bro Single Sofa",
    url: images.chairs.chairseven,
    generalCategery: "Chairs",
    categery: "Chairs",
    price: 980.0,
  },
  {
    id: 35,
    name: "Antero Black Double Sofa",
    url: images.sofas.sofaone,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 380.0,
  },
  {
    id: 36,
    name: "Castlery Double Sofa",
    url: images.sofas.sofatwo,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 620.0,
  },
  {
    id: 37,
    name: "Ellie Black Sinlge Sofa",
    url: images.sofas.sofathree,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 200.0,
  },
  {
    id: 38,
    name: "MGM Luxary Sofa",
    url: images.sofas.sofafour,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 720.0,
  },
  {
    id: 39,
    name: "Minotti Sofa Set",
    url: images.sofas.sofafive,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 670.0,
  },
  {
    id: 40,
    name: "Pompeii Deluxe Sinlge Sofa",
    url: images.sofas.sofasix,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 980.0,
  },
  {
    id: 41,
    name: "Sinkuku Sofa With Cushion",
    url: images.sofas.sofaseven,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 750.0,
  },
  {
    id: 41,
    name: "Tara Brown Single Sofa",
    url: images.sofas.sofaeight,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 320.0,
  },
  {
    id: 42,
    name: "Yuxin Sofa Set",
    url: images.sofas.sofanine,
    generalCategery: "Sofa",
    categery: "Sofa",
    price: 1200.0,
  },
  {
    id: 43,
    name: "Brothers Stylish Dinning Table",
    url: images.tables.tableone,
    generalCategery: "Table",
    categery: "table",
    price: 720.0,
  },
  {
    id: 44,
    name: "Aidan 6 Seater Dinning Table",
    url: images.tables.tabletwo,
    generalCategery: "Table",
    categery: "table",
    price: 720.0,
  },
  {
    id: 45,
    name: "Arlo Bedside Table",
    url: images.tables.tablethree,
    generalCategery: "Table",
    categery: "table",
    price: 42.0,
  },
  {
    id: 46,
    name: "Ava Bedside Table",
    url: images.tables.tablefour,
    generalCategery: "Table",
    categery: "table",
    price: 75.0,
  },
  {
    id: 47,
    name: "Bjorn Bedside Table",
    url: images.tables.tablefive,
    generalCategery: "Table",
    categery: "table",
    price: 60.0,
  },
  {
    id: 48,
    name: "Canyon Deluxe Dinning Table",
    url: images.tables.tablesix,
    generalCategery: "Table",
    categery: "table",
    price: 950.0,
  },
  {
    id: 49,
    name: "Hana Bedside Table",
    url: images.tables.tableseven,
    generalCategery: "Table",
    categery: "table",
    price: 120.0,
  },
  {
    id: 50,
    name: "Hudson Bedside Table",
    url: images.tables.tableeight,
    generalCategery: "Table",
    categery: "table",
    price: 80.0,
  },
  {
    id: 51,
    name: "Oliver Bedside Table",
    url: images.tables.tablenine,
    generalCategery: "Table",
    categery: "table",
    price: 50.0,
  },
];
